s3_bucket:
  train_data: wafer-train-data-5acbd2d
  logs: wafer-logs-4e1f3bd

log_dir: data_transform_train_logs

data_dir:
  train_good: good/train

log: 
  data_transform: train_data_transform_log.txt
  data_transform_main: data_transform_main.txt
  upload: upload_data_transform_train_log.txt

col:
  output: Output
  good_bad: Good/Bad
  wafer: Wafer
  unnamed: "Unnamed: 0"

