app:
  host: 0.0.0.0
  port: 8080

log:
  train_comp: train_comp.log
  train_pipeline: train_pipeline_log.log
  upload: upload_log.log

log_dir: app_logs

pipeline_path:
  pred: wafer-pred.zip
  train: wafer-train.zip

run_name: wafer-run

s3_bucket:
  components: wafer-components
  io_files: wafer-io-files
  logs: logs

templates:
  dir: templates
  index: index.html

train_components:
  clustering: wafer-clustering.yaml
  preprocessing: wafer-preprocess.yaml
  prod_model: wafer-prod.yaml
  raw_train_data_val: wafer-raw-data-val.yaml
  train_data_trans: wafer-train-data-transform.yaml
  train_db_op: wafer-train-db.yaml
  train_model: wafer-train.yaml
