app:
  host: 0.0.0.0
  port: 8080

log:
  train_comp: train_comp.txt
  train_pipeline: train_pipeline_log.txt
  upload: upload_log.txt

log_dir: app_logs

pipeline_path:
  pred: wafer-pred.zip
  train: wafer-train.zip

run_name: wafer-run

s3_bucket:
  components: wafer-kubeflow-components-4efdbdc
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd

templates:
  dir: templates
  index: index.html

train_components:
  clustering: wafer-clustering.yaml
  preprocessing: wafer-preprocess-train.yaml
  load_prod: wafer-prod.yaml
  raw_data_val: wafer-raw-data-val.yaml
  data_trans: wafer-train-data-transform.yaml
  db_operation: wafer-train-db.yaml
  model: wafer-train.yaml


pred_components:
  pred_data_trans: wafer-pred-data-transform.yaml
  pred_db_op: wafer-pred-db.yaml
  model: wafer-prediction.yaml
  preprocessing: wafer-preprocess-pred.yaml
  raw_data_val: wafer-raw-data-val.yaml
