app:
  host: 0.0.0.0
  port: 8080

log:
  train_comp: train_comp.txt
  train_pipeline: train_pipeline_log.txt
  pred_pipeline: pred_pipeline_log.txt
  upload: upload_log.txt

log_dir: app_logs

pipeline_path:
  pred: wafer_pred.zip
  train: wafer_train.zip

run_name: wafer_run

s3_bucket:
  components: wafer-kubeflow-components-4efdbdc
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd

templates:
  dir: templates
  index: index.html

train_components:
  clustering: wafer_clustering.yaml
  preprocessing: wafer_preprocess-train.yaml
  load_prod: wafer_prod.yaml
  raw_data_val: wafer_raw-data-val.yaml
  data_trans: wafer_train-data-transform.yaml
  db_operation: wafer_train-db.yaml
  model: wafer_train.yaml


pred_components:
  pred_data_trans: wafer_pred-data-transform.yaml
  pred_db_op: wafer_pred-db.yaml
  model: wafer_prediction.yaml
  preprocessing: wafer_preprocess-pred.yaml
  raw_data_val: wafer_raw_data_val.yaml