s3_bucket:
  train_data: wafer-train-data
  io_files: wafer-io-files
  logs: wafer-logs

files:
  train_export: train_input_file.csv

data_dir:
  train_good: good/train

log:
  db_insert: train_db_insert_log.log
  export_csv: train_export_to_csv_log.log
  train_main: training_main_log.log

mongodb:
  db_name: wafer-data
  collection_name: wafer-train-data
