s3_bucket:
  wafer_train_data: wafer-train-data-5acbd2d
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-71efbdd

log_dir: logs

data_dir:
  train_good: good/train

log: 
  db_train: wafer_db_train_log.txt
  data_transform: train_data_transform_log.txt
  train_main: training_main_log.txt
  upload: upload_log.txt

col:
  target: Output
  replace: Good/Bad
