s3_bucket:
  wafer_train_data: wafer-train-data
  io_files: wafer-io-files
  logs: wafer-logs

data_dir:
  good_data_train: good/train

logs_dir: logs

logs: 
  db_train: wafer_db_train_log.log
  data_transform: train_data_transform_log.log
  train_main: training_main_log.log

col:
  target: Output
  replace: Good/Bad
