s3_bucket:
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6

files:
  wafer_features: wafer_features.csv
  wafer_targets: wafer_targets.csv
  train_export: train_input_file.csv
  null_values: null_values.csv

target_col: Output

log:
  preprocess: preprocess_log.txt
  upload: upload_log.txt

knn_imputer:
  n_neighbors: 3
  weights: uniform

log_dir: logs
