s3_bucket:
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6

files:
  wafer_features: wafer_train_features.csv
  wafer_targets: wafer_train_targets.csv
  train_export: train_input_file.csv
  null_values: null_values.csv

target_col: Output

knn_imputer:
  n_neighbors: 3
  weights: uniform

dir:
  log: preprocess_train_logs

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO
