apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers: 
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /root/.aws/
  volumes:
    - name: aws-secret
      secret:
        secretName: aws-secret
