base:
  random_state: 355
  test_size: 0.33

target_col: Output

s3_bucket:
  io_files: wafer-io-files-03e0100
  model: wafer-model-3e502a3
  feature_store: wafer-feature-store-02126f6
  logs: wafer-logs-4e1f3bd

mlflow_config:
  exp_name: wafer
  run_name: mlops
  serialization_format: cloudpickle

models_dir:
  train: trained

file_pattern: wafer_train_features-

log:
  model_train: model_training.log
  upload: upload_model_train.log

log_dir: model_training_logs

model_utils:
  verbose: 3
  cv: 4
  n_jobs: -1

save_format: .sav

RandomForestClassifier:
  n_estimators:
    - 10
    - 50
    - 100
    - 130

  criterion:
    - gini
    - entropy

  max_features:
    - auto
    - log2

  max_depth:
    - 2
    - 3

XGBClassifier:
  learning_rate:
    - 0.5
    - 0.1
    - 0.01
    - 0.001

  max_depth:
    - 3
    - 5
    - 10
    - 20

  n_estimators:
    - 10
    - 50
    - 100
    - 200