s3_bucket:
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd
  raw_train_data: wafer-raw-data-140436f
  train_data: wafer-train-data-5acbd2d

dir:
  raw_train_batch_data: train_batch
  train_good_data: good/train
  train_bad_data: bad/train
  log: raw_train_data_validation_logs

files:
  train_schema: wafer-schema_training.json
  regex: wafer-regex.txt

log:
  upload: upload_raw_train_data_validation.log
  raw_train_main: raw_train_main.log
  values_from_schema: train_values_from_schema.log
  general: train_general.log
  name_validation: train_name_validation.log
  col_validation: train_col_validation.log
  missing_values_in_col: train_missing_values_in_column.log
