s3_bucket:
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-71efbdd
  raw_train_data: wafer-raw-data-140436f
  train_data: wafer-train-data-5acbd2d

data_dir:
  raw_train_batch: train_batch
  train_good: good/train  
  train_bad: bad/train

files:
  train_schema: wafer-schema_training.json
  regex: wafer-regex.txt

log:
  train_main: train_main_log
  values_from_schema: values_from_schema_log
  general: general_log
  name_validation: train_name_validation_log
  col_validation: train_col_validation_log
  missing_values_in_col: train_missing_values_in_column