s3_bucket:
  io_files: wafer-io-files
  model: wafer_model

files:
  features: wafer_features.csv
  targets: wafer_targets.csv
  elbow_plot: K-Means_Elbow.png

logs:
  clustering: clustering_log.log

log_dir: logs

base:
  random_state: 42

model_dir:
  trained: trained/

KMeans:
  init: k-means++

max_clusters: 11

model_save_format: .sav

knee:
  curve: convex
  direction: decreasing


