s3_bucket:
  io_files: wafer-io-files-03e0100
  model: wafer-model-3e502a3
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6

files:
  features: wafer_train_features.csv
  targets: wafer_train_targets.csv
  elbow_plot: K-Means_Elbow_train.png

log:
  clustering: train_clustering_log.txt
  upload: upload_train_cluster_log.txt

log_dir: logs

base:
  random_state: 42

model_dir:
  trained: trained

KMeans:
  init: k-means++

max_clusters: 11

model_save_format: .sav

knee:
  curve: convex
  direction: decreasing


