s3_bucket:
  io_files: wafer-io-files-03e0100
  model: wafer-model-3e502a3
  logs: wafer-logs-4e1f3bd

files:
  features: wafer_features.csv
  targets: wafer_targets.csv
  elbow_plot: K-Means_Elbow.png

logs:
  clustering: clustering_log.txt
  upload: upload_log.txt

log_dir: logs

base:
  random_state: 42

model_dir:
  trained: trained/

KMeans:
  init: k-means++

max_clusters: 11

model_save_format: .sav

knee:
  curve: convex
  direction: decreasing


