s3_bucket:
  pred_data: wafer-pred-data-2648352
  logs: wafer-logs-4e1f3bd

log_dir: data_transform_pred_logs

data_dir:
  pred_good: good/pred

log:
  data_transform: pred_data_transform_log.txt
  data_transform_main: data_transform_main.txt
  upload: upload_data_transform_predlog.txt

col:
  output: Output
  good_bad: Good/Bad
  wafer: Wafer
  unnamed: "Unnamed: 0"
