s3_bucket:
  pred_data: wafer-pred-data-2648352
  logs: wafer-logs-4e1f3bd

dir:
  pred_good_data: good/pred
  log: data_transform_pred_logs

col:
  output: Output
  good_bad: Good/Bad
  wafer: Wafer
  unnamed: "Unnamed: 0"

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO
