models_dir:
  trained: trained
  stag: staging
  prod: production

model_save_format: .sav

mlflow_config:
  exp_name: wafer-ops

feature_pattern: wafer_features-

s3_bucket:
  model: wafer-model-3e502a3
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6

log:
  upload: upload_load_prod_model_log.txt
  load_prod_model: load_prod_model.txt

log_dir: load_prod_model_logs
