models_dir:
  trained: trained
  stag: staging
  prod: production

model_save_format: .sav

mlflow_config:
  exp_name : wafer-test

s3_bucket:
  io_files: wafer-io-files
  model: wafer_model

log:
  upload: upload_log.log
  load_prod_model: load_prod_model.log

log_dir: logs


