s3_bucket:
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6

files:
  pred_input: pred_input_file.csv
  pred_input_preprocess: pred_input_file_preprocess.csv
  null_values: null_values.csv
  pred_file: predictions.csv

target_col: Output

model_dir:
  prod: production

log:
  preprocess_pred: preprocess_pred_log.txt
  upload: upload_log.txt

knn_imputer:
  n_neighbors: 3
  weights: uniform

log_dir: preprocess_pred_logs
