s3_bucket:
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6

files:
  pred_input: pred_input_file.csv
  pred_input_preprocess: pred_input_file_preprocess.csv
  null_values: pred_null_values.csv
  pred_file: predictions.csv

target_col: Output

log:
  preprocess_pred: preprocess_pred.log
  upload: upload_preprocess_pred.log

knn_imputer:
  n_neighbors: 3
  weights: uniform

dir: 
  log: preprocess_pred_logs

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO