s3_bucket:
  pred_data: wafer-pred-data-2648352
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6
  
files:
  pred_export: pred_input_file.csv

data_dir:
  pred_good: good/pred

log_dir: db_operation_pred_logs

log:
  db_insert: pred_db_insert_log.txt
  export_csv: pred_export_to_csv_log.txt
  db_main: prediction_main_log.txt
  upload: upload_db_operation_pred_log.txt

mongodb:
  db_name: wafer-data
  collection_name: wafer-pred-data
