s3_bucket:
  pred_data: wafer-pred-data-2648352
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6
  
files:
  pred_export: pred_input_file.csv

data_dir:
  pred_good: good/pred

log_dir: db_operation_pred_logs

log:
  db_insert: pred_db_insert.log
  export_csv: pred_export_to_csv.log
  db_main: prediction_main.log
  upload: upload_db_operation_pred.log

mongodb:
  db_name: wafer-data
  collection_name: wafer-pred-data
