s3_bucket:
  train_data: wafer-train-data-5acbd2d
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6
  
files:
  train_export: train_input_file.csv

data_dir:
  train_good: good/train

log_dir: db_operation_train_logs

log:
  db_insert: train_db_insert_log.txt
  export_csv: train_export_to_csv_log.txt
  db_main: training_main_log.txt
  upload: upload_db_operation_train_log.txt

mongodb:
  db_name: wafer-data
  collection_name: wafer-train-data
