s3_bucket:
  train_data: wafer-train-data-5acbd2d
  logs: wafer-logs-4e1f3bd
  feature_store: wafer-feature-store-02126f6
  
files:
  train_export: train_input_file.csv

dir:
  train_good_data: good/train
  log: db_operation_train_logs

log_dir: db_operation_train_logs

log:
  db_insert: train_db_insert.log
  export_csv: train_export_to_csv.log
  db_main: train_db_main.log
  upload: upload_db_operation_train.log

mongodb:
  db_name: wafer-data
  collection_name: wafer-train-data
